spring:
  application:
    name: JuryScan-API-prod
  datasource:
    url: ${PG_URL_PROD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate # Only validate the db schema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    default-schema: public
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false

# Configurações personalizadas da aplicação
api:
  uri: /api/v1
  data-load:
    create-default-users: ${CREATE_DEFAULT_USERS:false}
    create-dump-data: ${CREATE_DUMP_DATA:false}
  security:
    token:
      secret: ${JWT_SECRET}

# Configurações do Google
google:
  gemini:
    api:
      key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_SECRET_KEY}

# Configurações do Stripe
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Actuator para health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      # Detalhes apenas para usuários autorizados
      show-details: when-authorized