spring:
  application:
    name: JuryScan-API-dev
  datasource:
    url: ${PG_URL_DEV}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # Only validate the db schema
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    default-schema: public
    locations: classpath:db/migration
    validate-on-migrate: false

server:
  port: ${SERVER_PORT:8080}
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.security: DEBUG

# Configurações personalizadas da aplicação
api:
  uri: /api/v1
  data-load:
    create-default-users: ${CREATE_DEFAULT_USERS:false}
    create-dump-data: ${CREATE_DUMP_DATA:false}
  security:
    token:
      secret: ${JWT_SECRET}
  integration:
    services:
      ai-analyzer:
        url: ${AI_ANALYZER_URL:}
        api-key: ${AI_ANALYZER_API_KEY:}
  pricing:
    analysis-cost: ${ANALYSIS_COST:1}

# Configurações do Google
google:
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_SECRET_KEY}

# Configurações do Stripe
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Actuator para monitoramento e debug (Desenvolvimento)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,mappings
  endpoint:
    health:
      show-details: always